version: "3"
services:
  game-server:
    build:
      context: ./game
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - ./game/.env
  state-service:
    build:
      context: ./state-service
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    env_file:
      - ./state-service/.env
  discord-bot:
    build:
      context: ./discord-bot
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
    env_file:
      - ./discord-bot/.env
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - game-server
      - state-service
